### ISSUE TITLE
Place the response block just under the request block

### ISSUE THREAD

**Issue by welcoMattic** [asvae/laravel-api-tester#23]
Hi!

I've lots of annotation on my routes, and my response block is placed after the end of the route info block.

It will be nice if you can move it juste under the request block ;)

**Comment by asvae** [comment]
@welcoMattic develop branch features foldable info.

![Foldable info](http://i.imgur.com/Z5QsIyX.png)

You may try it.

**Comment by welcoMattic** [comment]
In which version? It's not available on 2.0.3 :/

**Comment by asvae** [comment]
@welcoMattic
```
"asvae/laravel-api-tester": "dev-develop",
```

**Comment by welcoMattic** [comment]
@asvae I really prefer stable version. I'll wait your next tag ;) Thanks

**Comment by asvae** [comment]
@welcoMattic yeah. Won't take years, I guess.

BTW Next minor release is aimed towards refactoring and interface improvements. So we might think of scrollbars or maybe something even better.

**Comment by welcoMattic** [comment]
@asvae Is there a new release tag with this little useful feature? Thanks

**Comment by asvae** [comment]
@welcoMattic unfortunately no.
You can use this commit 8b6b12f7c305c91a7363a57fac2214f045d29f56

It's in dev branch because of temporary drop of firebase support. Other than that, it should have good stability.

Give me a notice if something's broken, I'll fix it promptly.

Also, you can bind your project to commit because most probably, no minor releases will be coming.
Next one will be big. At best in terms of new features, at worst in terms of feature drops and breaking changes : 3.

**Comment by welcoMattic** [comment]
Ok, thanks for update, I will wait the next big release ;)
